displayName=Thieving Stall Counter
author=adnapPanda
description=Tracks the amount of stalls thieved and pet chance
tags=thieving,stall,rocky,pet,tracker
version=1.0
plugins=com.thievingstallcounter.ThievingStallCounterPlugin
build=standard